### ISSUE TITLE
Leaver's method at large L

### ISSUE THREAD

**Issue by tomstratton1** [BlackHolePerturbationToolkit/SpinWeightedSpheroidalHarmonics#18]
I believe the default method (Leaver?) at large values of L (roughly 30) is returning an incorrect answer. Please see below for an example.

In[3]:= q0 = \[Pi]/3;
p0 = \[Pi]/4; (*angles*)
A0 = 1/10; (*rotation*)

In[6]:= N[SpinWeightedSpheroidalHarmonicS[0, 10, 2, A0, q0, p0, 
  Method -> "Eigenvalue"], 20]
N[SpinWeightedSpheroidalHarmonicS[0, 10, 2, A0, q0, p0, 
  Method -> "Leaver"], 20]
N[SpinWeightedSpheroidalHarmonicS[0, 10, 2, A0, q0, p0], 20]

Out[6]= 0.21806161979579023346 I

Out[7]= 0.21806161979579022191 I

Out[8]= 0.21806161979579022191 I

In[9]:= N[SpinWeightedSpheroidalHarmonicS[0, 30, 2, A0, q0, p0, 
  Method -> "Eigenvalue"], 20]
N[SpinWeightedSpheroidalHarmonicS[0, 30, 2, A0, q0, p0, 
  Method -> "Leaver"], 20]
N[SpinWeightedSpheroidalHarmonicS[0, 30, 2, A0, q0, p0], 20]

Out[9]= -0.33377762330017136822 I

Out[10]= -2.9620325738622202404*10^-19

Out[11]= -2.9620325738622202404*10^-19

**Comment by barrywardell** [comment]
Thanks for reporting this. I can reproduce the problem and yes when you work with arbitrary precision numbers Leaver's method is the default for the harmonic (the eigenvalue uses a hybrid of the "Leaver" and "Eigenvalue" methods).

A couple of other interesting/strange observations:

1. The correct result is obtained if you work to higher precision (e.g. 128 digits instead of 20).
2. Once the correct result is obtained once (e.g. using 128 digits), dropping back down to 20 digits continues to reproduce the correct result.

The latter of these is particularly mysterious and I don't have a good explanation right now.

**Comment by barrywardell** [comment]
Here is a simple example demonstrating the weirdness in 2 above:
```Mathematica
q0 = \[Pi]/3;
p0 = \[Pi]/4;
A0 = 1/10; 
N[SpinWeightedSpheroidalHarmonicS[0, 30, 2, A0, q0, p0], 20]
N[SpinWeightedSpheroidalHarmonicS[0, 30, 2, A0, q0, p0], 128]
N[SpinWeightedSpheroidalHarmonicS[0, 30, 2, A0, q0, p0], 20]
```
The last line produces a different result from the third last line, and the result from the last line appears to be correct.

**Comment by barrywardell** [comment]
The weirdness appears to be due to internal caching. Running ClearSystemCache[] clears it.
